# Generated by Django 5.1.4 on 2025-01-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_disease_delete_treatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="gradcam_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
